experiment_name: ksparse_parity_1511_new2_t001
seed: 123
device: cpu

dataset:
  d: 35
  k: 4
  n_train: 75000
  n_val: 500
  n_test: 2000
  label_noise: 0.0
  x_dist: pm1   # or: bernoulli01

model:
  widths: [256,256]
  activation: relu  # Options: relu, gelu, tanh, sigmoid, elu
  bias: false

training:
  algo: sgd  # Only 'sgd' is supported
  epochs: 800
  batch_size: 4096
  lr_w: 7e-4  # Learning rate for SGD
  loss: mse   # squared loss (labels in {-1,+1})

logging:
  eval_every_cycle: true
  save_checkpoints: true
